## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [3]:
A = np.array([[2,7],[3,1]])
A

array([[2, 7],
       [3, 1]])

In [13]:
B = np.array([[2,7,3],[3,1,1]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [ ]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""


In [10]:
def shape_2x2(matrix):
    if matrix.shape == (2,2):
        return True
    else:
        return False

In [15]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [ ]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""


In [16]:
def determinant_2x2(matrix):
    if shape_2x2(matrix) == True:
        deter = float(np.linalg.det(matrix))
        return deter

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [18]:
determinant_2x2(A)

-18.999999999999996

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [19]:
eigenvals, V = np.linalg.eig(A)

**Task:** Print the eigenvalues.

In [20]:
print(eigenvals)

[ 6.10977223 -3.10977223]


**Task:** Print  the eigenvectors.

In [21]:
print(V)

[[ 0.86235788 -0.80769951]
 [ 0.50629921  0.58959436]]


**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [23]:
A

array([[2, 7],
       [3, 1]])

In [24]:
A[1][1]

1

In [ ]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

In [34]:
def eig_2x2(matrix):
    tup = ()
    if shape_2x2(matrix) == True:
        deter = determinant_2x2(matrix)
        a = matrix[0][0]
        d = matrix[1][1]
        trace = a + d
        eigenval1 = (trace + np.sqrt(trace**2 - 4(deter)))/2
        eigenval2 = (trace - np.sqrt(trace**2 - 4(deter)))/2
        vector = np.array[[x][y]]
        x = 
        #eigenvect = 
        return tup + (eigenval1,eigenval2) +

In [37]:
#new function of just using modules after talk with simon
    #Just understand concepts
def eig_2x2(matrix):
    tup = ()
    if shape_2x2(matrix) == True:
        eigenvals, eigenVec = np.linalg.eig(matrix)
        return tup + (eigenvals, ) + (eigenVec,)

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [38]:
eig_2x2(A)

(array([ 6.10977223, -3.10977223]),
 array([[ 0.86235788, -0.80769951],
        [ 0.50629921,  0.58959436]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [40]:
np.allclose(eigenvals, eig_2x2(A)[0])

True

In [41]:
np.allclose(V, eig_2x2(A)[1])

True

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [42]:
B = np.array([[0,1],[-1,0]])
B

array([[ 0,  1],
       [-1,  0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [44]:
eigenvals2, V2 = np.linalg.eig(B)
print(eigenvals2)
print(V2)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]


In [43]:
two = eig_2x2(B)
two

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [46]:
np.allclose(eigenvals2, two[0])

True

In [45]:
np.allclose(V2, two[1])

True

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [47]:
print(eigenvals)
print(eigenvals2)

[ 6.10977223 -3.10977223]
[0.+1.j 0.-1.j]


In [48]:
print(V)
print(V2)

[[ 0.86235788 -0.80769951]
 [ 0.50629921  0.58959436]]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]
