## Matrix Decomposition Exercise

In [1]:
# import numpy
import numpy as np

**Task:** Generate a random matrix 'A' with a shape of 150x50, using the '**np.random.rand**' function.

In [2]:
A = np.random.rand(150, 50)
A

array([[0.53356364, 0.81885834, 0.51654593, ..., 0.39357171, 0.86798056,
        0.67995818],
       [0.46779804, 0.35127796, 0.92843421, ..., 0.44177699, 0.82274664,
        0.18698112],
       [0.33808192, 0.7384277 , 0.95777946, ..., 0.88094914, 0.9811531 ,
        0.97971287],
       ...,
       [0.57559088, 0.82794633, 0.15147343, ..., 0.2580329 , 0.7150374 ,
        0.61255491],
       [0.98649868, 0.37937572, 0.77976526, ..., 0.27246044, 0.09198796,
        0.3116645 ],
       [0.65676158, 0.53346632, 0.41518567, ..., 0.83666643, 0.24800015,
        0.99506324]])

**Task:** Check the shape of 'A'.

In [3]:
A.shape

(150, 50)

**Task:** Decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V).

In [4]:
U, D, V = np.linalg.svd(A)

**Task:** Check the shapes of matrices U,D,V.

In [5]:
print(U.shape)
print(D.shape)
print(V.shape)

(150, 150)
(50,)
(50, 50)


**Task:** Reconstruct matrix 'A' from matrices U,D,V.

In [17]:
recon = np.matrix(U[:,:1])*np.diag(D[:1])*np.matrix(V[:1,:])

**Task:** Compare matrices 'A' and 'A_rec' with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [18]:
np.allclose(A, recon)

False

**Task:** Reduce the dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations).

In [20]:
B= np.random.rand(150, 20)
B

array([[0.42082167, 0.82109969, 0.95392236, ..., 0.67081963, 0.92552248,
        0.29647452],
       [0.60659228, 0.3432516 , 0.87229948, ..., 0.04002042, 0.48144976,
        0.63562247],
       [0.1453013 , 0.83699092, 0.04322865, ..., 0.94826114, 0.26816662,
        0.19711418],
       ...,
       [0.1422942 , 0.06997775, 0.24951963, ..., 0.51777736, 0.71746176,
        0.70010982],
       [0.37052001, 0.69566737, 0.45646907, ..., 0.55796192, 0.98150437,
        0.63276806],
       [0.16618723, 0.19101905, 0.94199568, ..., 0.76979936, 0.86734757,
        0.20858116]])

**Task:** Print the shape.

In [21]:
B.shape

(150, 20)

**Task:** Compare the two results with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [26]:
U, D, V = np.linalg.svd(B)
recon2 = np.matrix(U[:,:1])*np.diag(D[:1])*np.matrix(V[:1,:])

In [27]:
np.allclose(B, recon2)

False

**Task:** Filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape of (150x50)).

In [28]:
noise = np.random.normal(150, 50, len(A))

**Task:** Check the shape.

In [29]:
noise.shape

(150,)

In [32]:
A.shape

(150, 50)

**Task:** Define the function `'SVD'` which perform singular values decomposition.

Do not forget to hceck the shape of the input matrix.

In [ ]:
"""
PARAMS:
    A (numpy.ndarray) - matrix to decompose
RETURN:
    U (numpy.ndarray) - left singular vectors
    SV (numpy.ndarray) - singular values
    V (numpy.ndarray) - right singular vectors
"""

In [30]:
def new_svd(matrix):
    tup = ()
    U, SV, V = np.linalg.svd(matrix)
    return tup + (U,) + (SV,) + (V,)

**Task:** Call the function `'SVD'` on matrix 'A'.

In [31]:
new_svd(A)

(array([[-0.08419352,  0.05145044,  0.01742691, ..., -0.15718856,
         -0.16190034,  0.00769896],
        [-0.0819176 , -0.00998075,  0.06360614, ...,  0.09049696,
          0.00195599,  0.07359598],
        [-0.08720063,  0.15339324, -0.03079816, ...,  0.03946616,
         -0.06052292,  0.05034422],
        ...,
        [-0.08310241, -0.02248091,  0.01004378, ...,  0.65110007,
         -0.03277304,  0.04268566],
        [-0.08740129, -0.04920455, -0.04501443, ..., -0.03156415,
          0.6457848 , -0.04505016],
        [-0.0755078 , -0.05698101, -0.14796125, ...,  0.02954367,
         -0.03119569,  0.66461388]]),
 array([44.13531986,  5.42239364,  5.10239557,  5.08437103,  4.9041179 ,
         4.81162652,  4.69416419,  4.58974257,  4.52440483,  4.46359541,
         4.37409281,  4.24099555,  4.20635548,  4.18007161,  4.17544408,
         4.03380318,  3.97456051,  3.84539836,  3.81060136,  3.67038458,
         3.64423155,  3.56766257,  3.55666048,  3.52217642,  3.46600388,
        